name: minimal

channels:

  - conda-forge

  - defaults

dependencies:

  - colorlover=0.2.1

  - ipywidgets=7.4.0

  - notebook=5.6.0

  - numpy=1.15.1

  - numpy-base=1.15.1

  - pandas=0.23.4

  - pip=10.0.1

  - plotly=3.1.1

  - python=3.6.6

  - python-dateutil=2.7.3

  - scikit-learn=0.19.1

  - scipy=1.1.0

  - statsmodels=0.9.0

  - xlrd=1.1.0