name: minimal

channels:
- conda-forge
- defaults
- conda-forge/label/rc

dependencies:
- colorlover=0.2.1
- ipywidgets=7.4.0
- numpy=1.15.1
- numpy-base=1.15.1
- pandas=0.23.4
- plotly=3.1.1
- python=3.6.6
- python-dateutil=2.7.3
- scipy=1.1.0
- statsmodels=0.9.0
- xlrd=1.1.0

- pip:
  -scikit-learn==0.20rc1


