name: minimal
channels:
  - conda-forge
  - defaults
dependencies:
  - colorlover=0.2.1
  - ipywidgets
  - numpy=1.15.1
  - pandas=0.23.4
  - plotly=3.2.1
  - python=3.6.6
  - scipy=1.1.0
  - statsmodels=0.9.0
  - xlrd=1.1.0
  - openpyxl
  - pip:
    - scikit-learn==0.20rc1
    - fancyimpute
    - impyute
    - prince
    - findiff
