name: base
channels:
  - cimcb
  - conda-forge
  - cvxgrp
  - defaults
dependencies:
  - fancyimpute=0.3.1
  - knnimpute=0.1.0
  - colorlover=0.2.1
  - cufflinks-py=0.13.0
  - dash=0.22.0
  - dash-renderer=0.13.0
  - flask-compress=1.4.0
  - hdbscan=0.8.15
  - ipywidgets=7.4.0
  - missingno=0.4.1
  - py4j=0.10.7
  - widgetsnbextension=3.4.0
  - cvxpy=0.4.9
  - multiprocess=0.70.4
  - scs=1.2.6
  - _tflow_1100_select=0.0.2
  - _tflow_190_select=0.0.3
  - absl-py=0.4.0
  - alabaster=0.7.11
  - anaconda-client=1.7.1
  - anaconda-navigator=1.8.7
  - anaconda-project=0.8.2
  - anyqt=0.0.8
  - appnope=0.1.0
  - appscript=1.0.1
  - asn1crypto=0.24.0
  - astor=0.7.1
  - astroid=2.0.4
  - astropy=3.0.4
  - atomicwrites=1.2.0
  - attrs=18.1.0
  - automat=0.7.0
  - babel=2.6.0
  - backcall=0.1.0
  - backports=1.0
  - backports.shutil_get_terminal_size=1.0.0
  - beautifulsoup4=4.6.3
  - bitarray=0.8.3
  - bkcharts=0.2
  - blas=1.0
  - blaze=0.11.3
  - bleach=2.1.4
  - blosc=1.14.4
  - bokeh=0.13.0
  - boto=2.49.0
  - bottleneck=1.2.1
  - bzip2=1.0.6
  - ca-certificates=2018.03.07
  - certifi=2018.8.24
  - cffi=1.11.5
  - chardet=3.0.4
  - click=6.7
  - cloudpickle=0.5.5
  - clyent=1.2.2
  - colorama=0.3.9
  - commonmark=0.7.5
  - conda=4.5.11
  - conda-build=3.13.0
  - conda-env=2.6.0
  - conda-verify=3.1.0
  - constantly=15.1.0
  - contextlib2=0.5.5
  - cryptography=2.3.1
  - cryptography-vectors=2.3.1
  - curl=7.61.0
  - cvxcanon=0.1.1
  - cycler=0.10.0
  - cython=0.28.5
  - cytoolz=0.9.0.1
  - dask=0.18.2
  - dask-core=0.18.2
  - datashape=0.5.4
  - dbus=1.13.2
  - decorator=4.3.0
  - dill=0.2.8.2
  - distributed=1.22.1
  - docutils=0.14
  - ecos=2.0.5
  - entrypoints=0.2.3
  - et_xmlfile=1.0.1
  - expat=2.2.6
  - fastcache=1.0.2
  - filelock=3.0.6
  - flask=1.0.2
  - flask-cors=3.0.6
  - freetype=2.9.1
  - future=0.16.0
  - gast=0.2.0
  - get_terminal_size=1.0.0
  - gettext=0.19.8.1
  - gevent=1.3.6
  - glib=2.56.2
  - glob2=0.6
  - gmp=6.1.2
  - gmpy2=2.0.8
  - greenlet=0.4.14
  - grpcio=1.12.1
  - h5py=2.8.0
  - hdf5=1.10.2
  - heapdict=1.0.0
  - html5lib=1.0.1
  - hyperlink=18.0.0
  - icu=58.2
  - idna=2.7
  - imageio=2.3.0
  - imagesize=1.0.0
  - incremental=17.5.0
  - intel-openmp=2018.0.3
  - ipykernel=4.8.2
  - ipython=6.5.0
  - ipython_genutils=0.2.0
  - isort=4.3.4
  - itsdangerous=0.24
  - jbig=2.1
  - jdcal=1.4
  - jedi=0.12.1
  - jinja2=2.10
  - joblib=0.12.2
  - jpeg=9b
  - jsonschema=2.6.0
  - jupyter=1.0.0
  - jupyter_client=5.2.3
  - jupyter_console=5.2.0
  - jupyter_core=4.4.0
  - jupyter_dashboards_bundlers=0.9.1
  - jupyterlab=0.33.11
  - jupyterlab_launcher=0.11.2
  - keras=2.2.2
  - keras-applications=1.0.4
  - keras-base=2.2.2
  - keras-preprocessing=1.0.2
  - keyring=13.2.1
  - keyrings.alt=3.1
  - kiwisolver=1.0.1
  - lazy-object-proxy=1.3.1
  - libcurl=7.61.0
  - libcxx=4.0.1
  - libcxxabi=4.0.1
  - libedit=3.1.20170329
  - libffi=3.2.1
  - libgcc=4.8.5
  - libgfortran=3.0.1
  - libiconv=1.15
  - libpng=1.6.34
  - libprotobuf=3.6.0
  - libsodium=1.0.16
  - libssh2=1.8.0
  - libtiff=4.0.9
  - libxml2=2.9.8
  - libxslt=1.1.32
  - llvmlite=0.24.0
  - locket=0.2.0
  - lxml=4.2.4
  - lzo=2.10
  - markdown=2.6.11
  - markupsafe=1.0
  - matplotlib=2.2.3
  - maven=3.5.3
  - mccabe=0.6.1
  - mistune=0.8.3
  - mkl=2018.0.3
  - mkl-service=1.1.2
  - mkl_fft=1.0.4
  - mkl_random=1.0.1
  - more-itertools=4.3.0
  - mpc=1.1.0
  - mpfr=4.0.1
  - mpmath=1.0.0
  - msgpack-python=0.5.6
  - multipledispatch=0.6.0
  - navigator-updater=0.2.1
  - nbconvert=5.3.1
  - nbformat=4.4.0
  - ncurses=6.1
  - networkx=2.1
  - nltk=3.3.0
  - nodejs=8.11.3
  - nose=1.3.7
  - notebook=5.6.0
  - numba=0.39.0
  - numexpr=2.6.8
  - numpy=1.15.1
  - numpy-base=1.15.1
  - numpydoc=0.8.0
  - odo=0.5.1
  - olefile=0.45.1
  - openjdk=8.0.121
  - openpyxl=2.5.5
  - openssl=1.0.2p
  - orange3=3.15.0
  - packaging=17.1
  - pandas=0.23.4
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - parso=0.3.1
  - partd=0.3.8
  - path.py=11.0.1
  - pathlib2=2.3.2
  - patsy=0.5.0
  - pcre=8.42
  - pep8=1.7.1
  - pexpect=4.6.0
  - pickleshare=0.7.4
  - pillow=5.2.0
  - pip=10.0.1
  - pkginfo=1.4.2
  - plotly=3.1.1
  - pluggy=0.7.1
  - ply=3.11
  - prometheus_client=0.3.1
  - prompt_toolkit=1.0.15
  - protobuf=3.6.0
  - psutil=5.4.7
  - ptyprocess=0.6.0
  - py=1.5.4
  - pycodestyle=2.4.0
  - pycosat=0.6.3
  - pycparser=2.18
  - pycrypto=2.6.1
  - pycurl=7.43.0.2
  - pyflakes=2.0.0
  - pygments=2.2.0
  - pylint=2.1.1
  - pyodbc=4.0.24
  - pyopenssl=18.0.0
  - pyparsing=2.2.0
  - pyqt=5.9.2
  - pyqtgraph=0.10.0
  - pysocks=1.6.8
  - pytables=3.4.4
  - pytest=3.7.3
  - pytest-arraydiff=0.2
  - pytest-astropy=0.4.0
  - pytest-doctestplus=0.1.3
  - pytest-openfiles=0.3.0
  - pytest-remotedata=0.3.0
  - python=3.6.6
  - python-dateutil=2.7.3
  - python-louvain=0.11
  - python.app=2
  - pytz=2018.5
  - pywavelets=0.5.2
  - pyyaml=3.13
  - pyzmq=17.1.2
  - qt=5.9.6
  - qtawesome=0.4.4
  - qtconsole=4.4.1
  - qtpy=1.5.0
  - readline=7.0
  - requests=2.19.1
  - retrying=1.3.3
  - rope=0.11.0
  - ruamel_yaml=0.15.46
  - scikit-image=0.14.0
  - scikit-learn=0.19.1
  - scipy=1.1.0
  - seaborn=0.9.0
  - send2trash=1.5.0
  - serverfiles=0.2.1
  - setuptools=40.2.0
  - simplegeneric=0.8.1
  - singledispatch=3.4.0.3
  - sip=4.19.12
  - six=1.11.0
  - snappy=1.1.7
  - snowballstemmer=1.2.1
  - sortedcollections=1.0.1
  - sortedcontainers=2.0.4
  - sphinx=1.7.7
  - sphinxcontrib=1.0
  - sphinxcontrib-websupport=1.1.0
  - spyder=3.3.1
  - spyder-kernels=0.2.6
  - sqlalchemy=1.2.11
  - sqlite=3.24.0
  - statsmodels=0.9.0
  - sympy=1.2
  - tblib=1.3.2
  - tensorboard=1.10.0
  - tensorflow=1.10.0
  - tensorflow-base=1.10.0
  - termcolor=1.1.0
  - terminado=0.8.1
  - testpath=0.3.1
  - tk=8.6.8
  - toolz=0.9.0
  - tornado=5.1
  - traitlets=4.3.2
  - twisted=17.5.0
  - typed-ast=1.1.0
  - typing=3.6.4
  - unicodecsv=0.14.1
  - unixodbc=2.3.7
  - urllib3=1.23
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - werkzeug=0.14.1
  - wheel=0.31.1
  - wrapt=1.10.11
  - xlrd=1.1.0
  - xlsxwriter=1.0.8
  - xlwings=0.11.8
  - xlwt=1.2.0
  - xz=5.2.4
  - yaml=0.1.7
  - zeromq=4.2.5
  - zict=0.1.3
  - zlib=1.2.11
  - zope=1.0
  - zope.interface=4.5.0
  - pip:
    - appdirs==1.4.3
    - biopython==1.72
    - black==18.6b4
    - boto3==1.7.55
    - botocore==1.10.55
    - bz2file==0.98
    - cufflinks==0.13.0
    - docx2txt==0.7
    - gensim==3.5.0
    - jmespath==0.9.3
    - msgpack==0.5.6
    - nb-black==1.0.2
    - np-utils==0.5.5.0
    - oauthlib==2.1.0
    - odfpy==1.3.6
    - orange3-network==1.3.2
    - orange3-text==0.3.0
    - osqp==0.4.0
    - pdfminer3k==1.3.1
    - requests-oauthlib==1.0.0
    - s3transfer==0.1.13
    - setuptools-git==1.2
    - simhash==1.9.0
    - smart-open==1.6.0
    - tables==3.4.4
    - toml==0.9.4
    - tweepy==3.6.0
    - validate-email==1.3
    - wikipedia==1.4.0
